### ISSUE TITLE
re: menger sponge 

### ISSUE THREAD

**Issue by meta-androcto** [sugiany/blender_menger_sponge#1]
Hello, I am the Blender developer of add_mesh_extra_objects in Blender Release.
I would like to add your menger sponge addon into add_mesh_extra_objects in Blender Release.
It would be an very good inclusion.
I would ask your permission to merge your addon into add_mesh_extra_objects in Blender Release.
Thanks.
Brendon.

**Comment by sugiany** [comment]
Thank you very much for your interest in my addon.
Of course, you can merge my addon into your add_mesh_extra_objects. I hope it will be of some help for add_mesh_extra_objects.

**Comment by meta-androcto** [comment]
Thank you very much :)
